version: '3.8'
services:
  mcp-atlassian:
    image: ghcr.io/sooperset/mcp-atlassian:latest
    command: --transport sse --port 8080 -vv
    environment:
      # Atlassian Cloud Authentication
      - CONFLUENCE_URL=${CONFLUENCE_URL}
      - CONFLUENCE_USERNAME=${CONFLUENCE_USERNAME}
      - CONFLUENCE_API_TOKEN=${CONFLUENCE_API_TOKEN}
      # SSE Support
      - ENABLE_SSE=true
#      - JIRA_URL=${JIRA_URL}
#      - JIRA_USERNAME=${JIRA_USERNAME}
#      - JIRA_API_TOKEN=${JIRA_API_TOKEN}

      # Optional Configuration
#      - CONFLUENCE_SPACES_FILTER=DEV,TEAM,DOC
#      - JIRA_PROJECTS_FILTER=PROJ,DEV,SUPPORT
#      - READ_ONLY_MODE=false
#      - MCP_VERBOSE=false
    volumes:
      - ~/.mcp-atlassian:/home/app/.mcp-atlassian
    ports:
      - "8089:8080"
    restart: unless-stopped
